export enum TableColumnNames {
  CUSTOMER_NAME = 'CUSTOMER_NAME',
  EMISSIONS = 'EMISSIONS',
  SECTOR = 'SECTOR',
  ALLOCATION_METHOD = 'ALLOCATION_METHOD',
  STATUS = 'STATUS',
  ACTIONS = 'ACTIONS',
}
